This is makeindex, version 2.15 [MiKTeX 21.7].
Scanning style file ./ImmunoBERT.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ImmunoBERT.acn....done (466 entries accepted, 0 rejected).
Sorting entries.......done (4673 comparisons).
Generating output file ImmunoBERT.acr....done (191 lines written, 0 warnings).
Output written in ImmunoBERT.acr.
Transcript written in ImmunoBERT.alg.
